upstream news_node {
    server web:8000;
}

server {
    listen 80;

    # 정적 파일 (CSS, JS) 처리
    location /static/ {
        alias /app/static/;
    }

    # 미디어 파일 (이미지 업로드) 처리
    location /media/ {
        alias /app/media/;
    }

    # 나머지 요청은 Django(Gunicorn)으로 토스
    location / {
        proxy_pass http://news_node;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}