# Generated by Django 5.2.10 on 2026-01-26 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='region',
            field=models.CharField(choices=[('KR', 'South Korea'), ('AU', 'Australia')], default='KR', help_text='서비스 지역 (KR: 한국, AU: 호주)', max_length=10),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['region'], name='news_articl_region_900dd3_idx'),
        ),
    ]
