# Generated by Django 5.2.10 on 2026-02-04 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_region_article_news_articl_region_900dd3_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.URLField(help_text='방문한 기사 URL', max_length=500)),
                ('region', models.CharField(choices=[('KR', 'South Korea'), ('AU', 'Australia')], default='KR', max_length=10)),
                ('dwell_time', models.IntegerField(default=0, help_text='체류 시간 (초 단위)')),
                ('scroll_depth', models.IntegerField(default=0, help_text='스크롤 깊이 (0~100%)')),
                ('click_count', models.IntegerField(default=0, help_text='페이지 내 클릭/상호작용 횟수')),
                ('is_valid_view', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='로그 발생 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='news_userac_user_id_9215fe_idx'), models.Index(fields=['article_url'], name='news_userac_article_29a41e_idx'), models.Index(fields=['region'], name='news_userac_region_62f2a7_idx')],
            },
        ),
    ]
