# Generated by Django 5.2.11 on 2026-02-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
