# Generated by Django 5.2.11 on 2026-02-05 03:39

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_useractionlog_category_useractionlog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, help_text='AI 분류', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='기사 본문', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='region',
            field=models.CharField(choices=[('KR', 'South Korea'), ('AU', 'Australia')], default='KR', help_text='서비스 지역', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True, help_text='기사 원본 링크', max_length=1000),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='article_url',
            field=models.URLField(help_text='방문한 기사 URL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='dwell_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='scroll_depth',
            field=models.IntegerField(default=0),
        ),
    ]
