# Generated by Django 5.2.11 on 2026-02-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_category_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('USER', '사용자 직접 저장'), ('RSS', 'RSS 자동 수집')], default='USER', help_text='기사 수집 출처 (RSS: 추천 후보군, USER: 사용자 보관함)', max_length=10),
        ),
    ]
