# Generated by Django 5.2.11 on 2026-02-06 04:59

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='embedding',
            new_name='embedding_openai',
        ),
        migrations.AddField(
            model_name='article',
            name='embedding_pytorch',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
