# Generated by Django 5.2.11 on 2026-02-07 11:12

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_embedding_article_embedding_openai_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_user', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('embedding_user_openai', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='useractionlog',
            name='news_userac_region_62f2a7_idx',
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='action',
            field=models.CharField(choices=[('CLICK', '단순 클릭'), ('READ', '정독 (체류시간 김)'), ('SAVE', '요약 및 저장')], default='CLICK', max_length=20),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='article',
            field=models.ForeignKey(blank=True, help_text='내부 DB에 존재하는 기사일 경우 연결', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='news.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='region',
            field=models.CharField(choices=[('KR', 'South Korea'), ('AU', 'Australia')], default='KR', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('USER', '사용자 직접 저장'), ('RSS', 'RSS 자동 수집')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='dwell_time',
            field=models.IntegerField(default=0, help_text='초 단위 체류시간'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='is_valid_view',
            field=models.BooleanField(default=False, help_text='유효한 조회 여부(예: 10초 이상)'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='scroll_depth',
            field=models.IntegerField(default=0, help_text='스크롤 내린 깊이(%)'),
        ),
        migrations.AddIndex(
            model_name='useractionlog',
            index=models.Index(fields=['action'], name='news_userac_action_cb944e_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
