# Generated by Django 5.2.11 on 2026-02-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('FACT', '단순 보도 (Fact)'), ('INSIGHT', '심층 분석 (Insight)'), ('OPINION', '사설/칼럼 (Opinion)'), ('TUTORIAL', '가이드/팁 (How-to)')], default='FACT', help_text='기사의 성격 (Fact vs Insight)', max_length=20),
        ),
    ]
