# Generated by Django 5.2.11 on 2026-02-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
